### ISSUE TITLE
Audio + touchpad and maybe display on some GPUs chromebook

### ISSUE THREAD

**Issue by nando1973** [userminer2/EclipsedOS#1]
does audio work on chromebook?

**Comment by userminer2** [comment]
It should but I am not 100% sure given the fact I don't have a chromebook to test it but the kernel version used did work for me in the past.

**Comment by nando1973** [comment]
I have a chromebook and the audio does not work, but thanks

**Comment by nando1973** [comment]
Hello, the touchpad is slow, could you put the chromebook touchpad driver? sorry for my English

**Comment by nando1973** [comment]
thanks for your effort and thanks for your distro

**Comment by userminer2** [comment]
No problems try updating kernel using ukuu(I might make it preinstalled).
more info here:
https://github.com/teejee2008/ukuu

**Comment by userminer2** [comment]
Thanks for the feedback as it is hard to get an os to work when you don't really have feedback

**Comment by userminer2** [comment]
> Hello, the touchpad is slow, could you put the chromebook touchpad driver? sorry for my English

So far I have not noticed any problems with your english.

**Comment by userminer2** [comment]
> Hello, the touchpad is slow, could you put the chromebook touchpad driver? sorry for my English

How slow is the touchpad?

**Comment by nando1973** [comment]
the arrow moves a little slowly

**Comment by userminer2** [comment]
What model do you have?

**Comment by nando973** [comment]
hello, hp 11a g6 ee

**Comment by nando973** [comment]
amd

**Comment by nando973** [comment]
AMD Stoney Ridge chipset

**Comment by userminer2** [comment]
thanks
I have updated the kernel and it should work a bit better.

**Comment by nando1973** [comment]
Ok Thanks I will try

**Comment by userminer2** [comment]
So how did it go?

**Comment by nando973** [comment]
sorry i haven't tried it yet

**Comment by userminer2** [comment]
It's ok

**Comment by nando973** [comment]
Hello I try, the touchpad run better, but the video is lagging and have not audio. Thank you for your effort

**Comment by userminer2** [comment]
Alright how bad is the video and what gpu does your chromebook have. I am sorry I don't know much about Amd gpus.
And I will make an Intel/amd release.

And thank you so much for being the only one to have tested and reported bugs to my knowledge.

**Comment by nando1973** [comment]
Procesador[AMD A4-9120C](https://www.notebookcheck.org/AMD-Bristol-Ridge-A4-9120C-Notebook-Processor.478536.0.html) 2 x 1.6 - 2.4 GHz, Stoney Ridge
Adaptador gráficoAMD Radeon R4 (Stoney Ridge)

**Comment by nando1973** [comment]
Thank you

**Comment by userminer2** [comment]
How did you test it?
By that I mean was it on a usb or full install because there is a way to find out if it is a disk or gpu issue.

**Comment by userminer2** [comment]
Also side note to test if gpu works.
Try the command "install extremetuxracer" in terminal and try playing the game.
If it is playable(good frame rate and no lag or little lag) then I am not exactly sure but I can try to investigate.
If not then I will try to make an amd version of the OS.

EDIT: try changing kernels I will try to find a one command to copy and paste for you.

**Comment by userminer2** [comment]
Nevermind I think I was able to recreate the bug by running it on a vm on my 2008 imac.

It is severe screentearing with app windows not rendering correctly on higher resolutions.

Is that the bug or is that another thing to fix?
EDIT: GPU is ATI radeon 2400 XT

**Comment by nando1973** [comment]
I tried it without installing, the vídeo is freezing without sound. Thank you so much for your effort. The distro is amazing.

**Comment by userminer2** [comment]
what usb do you have as this might be linked

**Comment by userminer2** [comment]
On usb 2.0 (grey port or grey plug instead of blue) you can encounter issues.
EDIT: blue port is usb 3.0 and higher and your chromebook model should have it.

**Comment by nando1973** [comment]
I tried it with usb 2.0, next time I will try it with usb 3.0. Thanks for your replies

**Comment by userminer2** [comment]
Your welcome,
Working on a beta for version 1.1 where I try to make the OS need less vram and ram.
How was it even usable on usb 2.0? I swear even chromeOS was borderline unusable on usb2.0. If you test or even want to install it It is HIGHLY reccomended you use a usb3.0 and a 3.0 port for decent performance.
